name: C++ Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check C++ files format
      run: |
        find . -regex '.*\.\(cpp\|h\)' -exec clang-format -style=file -i {} +
        git diff --exit-code